apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "tc-otel.fullname" . }}
  labels:
    {{- include "tc-otel.labels" . | nindent 4 }}
data:
  config.json: |
    {{- .Values.config | toPrettyJson | nindent 4 }}
