apiVersion: 1

datasources:
  - name: VictoriaLogs
    uid: victoria-logs
    type: victoriametrics-logs-datasource
    access: proxy
    url: http://victoria-logs:9428
    editable: true
    jsonData:
      maxLines: 1000
